import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// iOS Safari can leave `position: fixed` elements (like the Capture drawer's
// overlay) visually detached from the viewport after the on-screen keyboard
// opens/closes, because by default the keyboard only shrinks the *visual*
// viewport while the layout viewport (which fixed elements are positioned
// against) stays unchanged. `resizes-content` makes the keyboard resize the
// layout viewport too, so fixed positioning stays correct.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 dark:bg-black">
        {children}
      </body>
    </html>
  );
}
